# Generated by Django 3.1.1 on 2020-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
