# Generated by Django 3.1.2 on 2020-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20201210_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=50)),
                ('meal', models.CharField(max_length=50)),
            ],
        ),
    ]
