# Generated by Django 3.1.4 on 2021-01-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20201212_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='name',
        ),
    ]
